version: 'version'

services:
  db:
    image: mysql:8.0
    container_name: multimedia_managment_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=multimedia_management
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  volumes:
    db_data: 