spring:
  application:
    name: multimedia-management

  datasource:
    url: jdbc:mysql://db:3306/multimedia_management
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
